-- USER (USER_ID, EMAIL, PASSWORD)

-- ROLE (ROLE_ID, ROLE_TITLE)

-- ROLE_USER(ROLE_USER_ID,USER_ID, ROLE_ID)

-- TYPE(TYPE_ID,TYPE_NAME)

-- POST (POST_ID, POST_TITLE, POST_CONTENT, POST_AUTHOR_ID, POST_ORIGIN, POST_TYPE_ID)

-- VIDEO(VIDEO_ID, VIDEO_TITLE, VIDEO_CONTENT, VIDEO_AUTHOR_ID, VIDEO_ORIGIN, VIDEO_TYPE_ID)

-- USER_POST(USER_POST_ID,USER_ID,POST_ID)

-- USER_VIDEO(USER_VIDEO_ID,USER_ID,VIDEO_ID)

-- COMMENT (COMMENT_ID, COMMENT_BODY, COMMENT_USER_ID, COMMENT_POST_ID, COMMENT_PARENT_ID)
